deploy issue

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -22,7 +22,20 @@ jobs:
       - name: Add VPS to known_hosts
         run: |
           mkdir -p ~/.ssh
-          ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts
+          chmod 700 ~/.ssh
+
+          if [ -z "${{ secrets.HOST }}" ]; then
+            echo "HOST secret is empty!"
+            exit 1
+          fi
+
+          ssh-keyscan -p 22 -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts 2>/dev/null || {
+            echo "ssh-keyscan failed"
+            exit 1
+          }
+
+          chmod 644 ~/.ssh/known_hosts
+
 
       - name: Deploy to VPS
         run: |
